#!/usr/bin/python3
import csv
import os
import time
import json
import urllib.request
import gc

def updategroups():
        output={}
        bm_groups={}
        DMRp_groups={}
        FreeDMR_groups={}
        SystemX_groups={}
        TGIF_groups={}
        keys = ['tg', 'name']
	
        #TGIF has commas in group names which messes up CSV file parsing
        #so we need to get the JSON version of their TGList as its easier to parse
        url="https://api.tgif.network/dmr/talkgroups/json"
        filename = "/usr/local/etc/TGList_TGIF.json"
        with urllib.request.urlopen(url) as response, open(filename, 'wb') as outfile:
                data = response.read()
                outfile.write(data)
        del data

        f = open("/usr/local/etc/BM_TGs.json", "r")
        bm_raw = json.load(f)
        bm_groups.update(bm_raw)
        f.close()
        output.update(bm_groups)
        del bm_groups
        del bm_raw

        f = open("/usr/local/etc/TGList_DMRp.txt", "r")
        DMRp_raw = csv.DictReader(f, fieldnames=keys)
        for row in DMRp_raw:
                DMRp_groups[row["tg"]]=row["name"]
        f.close()
        output.update(DMRp_groups)
        del DMRp_groups
        del DMRp_raw

        f = open("/usr/local/etc/TGList_FreeDMR.txt", "r")
        FreeDMR_raw = csv.DictReader(f, fieldnames=keys)
        for row in FreeDMR_raw:
                FreeDMR_groups[row["tg"]] = row["name"]
        f.close()
        output.update(FreeDMR_groups)
        del FreeDMR_groups
        del FreeDMR_raw

        f = open("/usr/local/etc/TGList_SystemX.txt", "r")
        SystemX_raw = csv.DictReader(f, fieldnames=keys)
        for row in SystemX_raw:
                SystemX_groups[row["tg"]]=row["name"]
        f.close()
        output.update(SystemX_groups)
        del SystemX_groups
        del SystemX_raw

        f = open("/usr/local/etc/TGList_TGIF.json", "r")
        TGIF_raw = json.load(f)
        #Make the TGIF group ID's 7 digits with a prefix  of 5 since we're working with the original .json group list here
        for groups in TGIF_raw:
                groupid = groups.get('id').rjust(6, "0")
                groupid = groupid.rjust(7, "5")
                TGIF_groups[groupid] = groups.get('name')
        f.close()
        output.update(TGIF_groups)
        del TGIF_groups
        del TGIF_raw

        path = r"/usr/local/etc/groups.txt"
        file_out = open(path, "w")
        json.dump(output, file_out, indent=2, ensure_ascii=False)
        file_out.close()
        del output
        gc.collect()
        n_timestamp = os.path.getmtime(path)
        return(n_timestamp)

group_path = r"/usr/local/etc/groups.txt"
n_timestamp = os.path.getmtime(group_path)

while True:
        c_timestamp = os.path.getmtime(group_path)
        if (n_timestamp == c_timestamp):
                time.sleep(600)
        else:
                print ("Updating groups.txt")
                n_timestamp = updategroups()

